# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Preprocess": "00_preprocess.ipynb",
         "get_freq": "01_tfidf.ipynb",
         "form_matrix": "01_tfidf.ipynb",
         "get_query_vec": "01_tfidf.ipynb",
         "get_cos_sim": "01_tfidf.ipynb"}

modules = ["preprocess.py",
           "tfidf.py",
           "None.py"]

doc_url = "https://Sylvia9628.github.io/nbdev_testing/"

git_url = "https://github.com/Sylvia9628/nbdev_testing/tree/master/"

def custom_doc_links(name): return None
