# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"preprocess": "00_core.ipynb",
         "get_freq": "00_core.ipynb",
         "form_matrix": "00_core.ipynb",
         "get_query_vec": "00_core.ipynb",
         "get_cos_sim": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Sylvia9628.github.io/nbdev_testing/"

git_url = "https://github.com/Sylvia9628/nbdev_testing/tree/master/"

def custom_doc_links(name): return None
